<?xml version="1.0"?>
<Project ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <RuntimesCopy Include="$(MSBuildThisFileDirectory)\..\runtimes\**\*" />
  </ItemGroup>
  <Target Name="CopyNatives" AfterTargets="Build">
    <Copy SourceFiles="@(RuntimesCopy)"
      DestinationFolder="$(TargetDir)runtimes\%(RecursiveDir)"
      SkipUnchangedFiles="true" />
  </Target>
  <Target Name="PublishNatives" BeforeTargets="ComputeResolvedFilesToPublishList">
    <ItemGroup>
      <ResolvedFileToPublish Include="@(RuntimesCopy)">
        <RelativePath>runtimes\%(RecursiveDir)%(Filename)%(Extension)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
