.\" 
.\"    BassBoom  Copyright (C) 2025  Aptivi
.\" 
.\"    BassBoom is free software: you can redistribute it and/or modify
.\"    it under the terms of the GNU General Public License as published by
.\"    the Free Software Foundation, either version 3 of the License, or
.\"    (at your option) any later version.
.\"
.\"    BassBoom is distributed in the hope that it will be useful,
.\"    but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"    GNU General Public License for more details.
.\"
.\"    You should have received a copy of the GNU General Public License
.\"    along with this program.  If not, see <https://www.gnu.org/licenses/>.
.\"

.TH bassboom 1 "23 Feb 2024" "0.1.0" "BassBoom"
.SH NAME
bassboom \- Cross-platform music player written in C#
.SH SYNOPSIS
bassboom [args]
.SH DESCRIPTION
bassboom is the launcher for BassBoom, which is a cross-platform music player written in C#. The manual pages are not updated here, so you'll have to refer to the GitBook manual instead.
.SH DOCUMENTATION
The whole documentation can be found in https://aptivi.gitbook.io/bassboom-manual.
.SH AUTHOR
Aptivi (ceo AT aptivi DOT anonaddy DOT com)
