.\" 
.\"    BassBoom  Copyright (C) 2025  Aptivi
.\" 
.\"    BassBoom is free software: you can redistribute it and/or modify
.\"    it under the terms of the GNU General Public License as published by
.\"    the Free Software Foundation, either version 3 of the License, or
.\"    (at your option) any later version.
.\"
.\"    BassBoom is distributed in the hope that it will be useful,
.\"    but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"    GNU General Public License for more details.
.\"
.\"    You should have received a copy of the GNU General Public License
.\"    along with this program.  If not, see <https://www.gnu.org/licenses/>.
.\"

.TH bb-sndplay 1 "30 Apr 2026" "1.0.0" "BassBoom.QuickPlay"
.SH NAME
bb-sndplay \- Cross-platform tiny sound player written in C#
.SH SYNOPSIS
bb-sndplay [args]
.SH DESCRIPTION
bb-sndplay is the launcher for BassBoom.QuickPlay, which is a tiny sound player written in C#. The manual pages are not updated here, so you'll have to refer to the GitBook manual instead.
.SH DOCUMENTATION
The whole documentation can be found in https://aptivi.gitbook.io/bassboom-manual.
.SH AUTHOR
Aptivi (ceo AT aptivi DOT anonaddy DOT com)
