name: Build Project (Debian Package)

on:
  push:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x", "x/exp/libmpv" ]
  pull_request:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x", "x/exp/libmpv" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Install required packages
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo NEEDRESTART_SUSPEND=1 apt update
          sudo NEEDRESTART_SUSPEND=1 apt install devscripts debhelper-compat dput build-essential equivs
          sudo NEEDRESTART_SUSPEND=1 mk-build-deps -i
    
      - name: Initialize offline package
        run: |
          make init-offline
          make clean
        
      - name: Make original package
        run: |
          mv debian ..
          mv .github ..
          tar cfv ../bassboom-3_2.0.3.0-1.0.0.0.orig.tar .
          xz ../bassboom-3_2.0.3.0-1.0.0.0.orig.tar
          mv ../debian .

      - name: Build package
        run: |
          debuild --no-lintian -us -uc
          cp ../*.deb .
        
      - name: Upload package to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Application-BB-Debian-Package
          path: "*.deb"

      - name: Try to install
        run: |
          sudo apt install ./bassboom-3_*.deb
