name: Build MPG123 library (FreeBSD - ARM64)

on:
  push:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x" ]
  pull_request:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x" ]
    
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Build library in FreeBSD VM
        id: build-lib-arm64
        uses: vmactions/freebsd-vm@v1
        with:
          release: "15.0"
          arch: "aarch64"
          run: |
            pkg install -y autoconf automake
            cd assets/libmpg123 ; autoreconf -iv ; ./configure --disable-components --enable-libmpg123 --enable-libout123 --enable-libout123-modules ; make ; make install DESTDIR=$PWD/outlib
      - name: Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "MPG123 library"
          path: assets/libmpg123/outlib
