name: Build Project (Debug)

on:
  push:
    branches: [ "main", "x/exp/libmpv" ]
  pull_request:
    branches: [ "main", "x/exp/libmpv" ]
    
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Setup Mono (Unix)
        if: matrix.runs-on == 'ubuntu-latest'
        run: sudo apt install mono-complete
      - name: Setup real 7zip (macOS)
        if: matrix.runs-on == 'macos-latest'
        run: |
          curl -L --output 7z2409.tar.xz https://www.7-zip.org/a/7z2409-mac.tar.xz
          tar xvf 7z2409.tar.xz
          mkdir /usr/local/bin
          mv 7zz /usr/local/bin/7z
          chmod +x /usr/local/bin/7z
      - name: Solution Compilation (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: ./tools/build.cmd Debug -p:ContinuousIntegrationBuild=true
      - name: Solution Compilation (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: make dbg-ci
      - name: Testing
        run: dotnet test --no-build --configuration Debug
        
