name: Build Project (Release)

on:
  push:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x", "x/exp/libmpv" ]
  pull_request:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x", "x/exp/libmpv" ]
    
jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Setup Mono (Unix)
        if: matrix.runs-on == 'ubuntu-latest'
        run: sudo apt install mono-complete
      - name: Setup real 7zip (macOS)
        if: matrix.runs-on == 'macos-latest'
        uses: milliewalky/setup-7-zip@v2
      - name: Solution Compilation (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: ./tools/build.cmd Release -p:ContinuousIntegrationBuild=true
      - name: Solution Compilation (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: make rel-ci
      - name: Testing
        run: dotnet test --no-build --configuration Release
