name: Build MPG123 library (macOS - ARM64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setting up environment
        run: |
          brew install autoconf automake libtool
      - name: Setting up MPG123 library
        run: |
          curl -o mpg123.tar.bz2 https://www.mpg123.de/download/mpg123-1.32.6.tar.bz2
          tar xvf mpg123.tar.bz2
      - name: MPG123 compilation
        run: |
          cd mpg123-1.32.6 ; ./configure ; make
      - name: MPG123 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "MPG123 library - libmpg123"
          path: mpg123-1.32.6/src/libmpg123/.libs/libmpg123.0.dylib
      - name: MPG123 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "MPG123 library - libout123"
          path: mpg123-1.32.6/src/libout123/.libs/libout123.0.dylib
      - name: MPG123 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "MPG123 library - libout123 output modules"
          path: mpg123-1.32.6/src/libout123/modules/.libs/*.so
