name: Prepare release (canary)

on:
  push:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x", "x/exp/libmpv" ]
  pull_request:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x", "x/exp/libmpv" ]
    
jobs:
  build:

    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Release Asset Preparation
        run: |
          cmd.exe /c "tools\build.cmd Debug -p:ContinuousIntegrationBuild=true"
          dotnet build -p:Configuration=Debug -p:Platform=x64 public/BassBoom.Installers/BassBoom.Installer.sln
          dotnet build -p:Configuration=Debug -p:Platform=ARM64 public/BassBoom.Installers/BassBoom.Installer.sln
          Move-Item public/BassBoom.Installers/BassBoom.InstallerBundle/bin/x64/Debug/BassBoom.InstallerBundle.exe vnd/bassboom-win-x64-installer.exe
          Move-Item public/BassBoom.Installers/BassBoom.InstallerBundle/bin/ARM64/Debug/BassBoom.InstallerBundle.exe vnd/bassboom-win-arm64-installer.exe
      - uses: actions/upload-artifact@v4
        with:
          name: installer-x64-msi
          path: "vnd/bassboom-win-x64-installer.exe"
      - uses: actions/upload-artifact@v4
        with:
          name: installer-arm64-msi
          path: "vnd/bassboom-win-arm64-installer.exe"
      - uses: actions/upload-artifact@v4
        with:
          name: bb-build-dotnet
          path: "private/BassBoom.Cli/bin/Debug/net8.0"
      - uses: actions/upload-artifact@v4
        with:
          name: bb-build-dotnetfx
          path: "private/BassBoom.Cli/bin/Debug/net48"
      - name: Package Publication
        run: |
          dotnet nuget add source --username AptiviCEO --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Aptivi/index.json"
          cmd.exe /C "tools\push.cmd ${{ secrets.GITHUB_TOKEN }} github"
