name: Prepare release

on:
  push:
    tags:
      - '**'
    
jobs:
  build:

    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Setup DocFX
        run: dotnet tool install --global docfx
      - name: Release Asset Preparation
        run: |
          cmd.exe /c "tools\build.cmd Release -p:ContinuousIntegrationBuild=true"
          cmd.exe /c "tools\pack.cmd"
          cmd.exe /c "tools\docgen.cmd"
          cmd.exe /c "tools\docgen-pack.cmd"
          dotnet build -p:Configuration=Release -p:Platform=x64 public/BassBoom.Installers/BassBoom.Installer.sln
          dotnet build -p:Configuration=Release -p:Platform=ARM64 public/BassBoom.Installers/BassBoom.Installer.sln
          Move-Item public/BassBoom.Installers/BassBoom.InstallerBundle/bin/x64/Release/BassBoom.InstallerBundle.exe tools/bassboom-win-x64-installer.exe
          Move-Item public/BassBoom.Installers/BassBoom.InstallerBundle/bin/ARM64/Release/BassBoom.InstallerBundle.exe tools/bassboom-win-arm64-installer.exe
      - name: Release Preparation
        id: release-asset
        shell: bash
        run: |
          echo "SUBJECT=$(cat CHANGES.TITLE)" >> "$GITHUB_OUTPUT"
          echo 'BODY<<EOF' >> "$GITHUB_OUTPUT"
          cat CHANGES >> "$GITHUB_OUTPUT"
          powershell 'Get-FileHash -Algorithm sha256 tools/*.zip | % {"- " + $_.Hash + "  " + (Resolve-Path -Path $_.Path -Relative)}' >> "$GITHUB_OUTPUT"
          powershell 'Get-FileHash -Algorithm sha256 tools/*.exe | % {"- " + $_.Hash + "  " + (Resolve-Path -Path $_.Path -Relative)}' >> "$GITHUB_OUTPUT"
          echo 'EOF' >> "$GITHUB_OUTPUT"
      - name: Binary Attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'tools/*.zip'
      - name: Release Making
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.release-asset.outputs.BODY }}
          name: ${{ steps.release-asset.outputs.SUBJECT }}
          files: |
            tools/*.zip
            tools/*.exe
      - name: Package Publication
        run: cmd.exe /C "tools\push.cmd ${{ secrets.NUGET_APIKEY }}"
