name: Prepare release (canary)

on:
  push:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x", "x/exp/libmpv" ]
  pull_request:
    branches: [ "main", "x/oob/v0.1.x", "x/oob/v0.2.x", "x/exp/libmpv" ]
    
jobs:
  build:

    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Release Asset Preparation
        run: cmd.exe /c "tools\build.cmd Debug -p:ContinuousIntegrationBuild=true"
      - uses: actions/upload-artifact@v4
        with:
          name: bb-build
          path: "private/BassBoom.Cli/bin/Debug"
      - name: Package Publication
        run: |
          dotnet nuget add source --username AptiviCEO --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Aptivi/index.json"
          cmd.exe /C "tools\push.cmd ${{ secrets.GITHUB_TOKEN }} github"
